name: 'Colly Linkcheck'
description: 'Linkchecker using colly as a scraper'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.19.2"
    - run: go run main.go
      shell: bash