name: 'Colly Linkcheck'
description: 'Linkchecker using colly as a scraper'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "^1.19.2"
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ls
      shell: bash
    - run: go run main.go
      shell: bash