name: 'Colly Linkcheck'
description: 'Linkchecker using colly as a scraper'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "^1.19.2"
    - run: go run main.go
      shell: bash
      working-directory: ${{ github.action_path }}